language: go

go:
  - 1.1
  - tip


matrix:
  allow_failures:
    - go: tip

install:
  - go get -v github.com/xoebus/gocart/gocart
  - export PATH=$HOME/gopath/bin:$PATH
  - gocart install
  - go install github.com/onsi/ginkgo/ginkgo
  - go test -i ./...

script:
  - mkdir -p ./.rootfs
  - curl http://cfstacks.s3.amazonaws.com/lucid64.dev.tgz | tar zxf - -C ./.rootfs
  - export GARDEN_TEST_ROOTFS=$PWD/.rootfs
  - export PATH=$HOME/gopath/bin:$PATH
  - sudo ginkgo -race -r -i --randomizeAllSpecs
